// 64x64 grayscale portrait for the SVD compression island: Albert Einstein,
// 1921, photographed by Ferdinand Schmutzer (public domain, via Wikimedia
// Commons). Generated offline from the original photo; pixels ship as base64 so
// the exact same matrix is available in Node (verification) and the browser.

export const PORTRAIT_W = 64;
export const PORTRAIT_H = 64;

const PORTRAIT_B64 =
  'QkU8OyEFBQQDAwQEBAMDAgMDAQIBAQABAAEBAAAAAQABAAABAQICAwMDAgULEhITEwgEBQYICxEZISYhEAoPEkVFQj4gBQUE' +
  'BAQEBQYDAwIDAwIBAQEAAQABAQABAAAAAQABAAEDBAMICAMCCQ8JEhAGBAYLCwoQFyEqKBYJEBpGS0I9HwQEAwQFBAQFAwMD' +
  'AwEBAgECAQEAAQIAAAAAAQEBAQEABAYKDAsDAgUIDQ8TEgsMDQkJEBYbJSYaChAZRElCPx4EBAMEBAQEBAQEAQICAQICAQEB' +
  'AAABAQAAAQAAAQECAwQECQwNBQMGERgYGBkaFAgFEBoXGB4fHBMRGEVGPj8eBAQEAwMEBAQCAwICAwIBAQEBAAAAAQAAAAEA' +
  'AgEAAwwLBQUNEA8IBA0ZHBQPFhMIAw8aGx4iIyEbFxRER0NCGwMFBAQFBAUEAwMDAwICAgICAQEAAQEAAQECAQEBAQMICwYI' +
  'ERcWDwoKEhYSCQkNCgoQGR8mLioiGBEWRElCQhwDBQUEBAUGBQUDAgMEAwMCAgMCAQIBAQEBAgECBAgCAgQJCxARDxEREhIT' +
  'EQsEBgoUFhoiKjAqIBEKF0lMRUQgBgYFAwMEAwIDAgEAAQEAAAAAAAABAgEBAAABAwkKAwACDBIKBAEPGRkZGBoTBgQFEBsf' +
  'JSgoJRwPCw8hISYjGRcSEhwZGhgXFhMZFg0NDQ0MCg0GCQUCAQIGCAkKCQkEBA0SCgMEEhgaGRQTGA0FAwseIiUjICAeFAwR' +
  'BAQDBAUKCAYKEhYREhwXEBgQERYWFxwmICMbGxobIiAbICUgJygYFxQWGxsXHx8lJhcWCgMIFBwhHx4gIRsSFgkFBQgGBQUI' +
  'FBAWExQQEQIICBETCg0TExYUIR4XFxsgFA8TDQsNESMICQsRCwgKGRwJGRQFBRAXGxwhKCghFxQUDw0LBgoKCggREQsXDQoF' +
  'ChwgFwYKExENEiglHhwoJR4WDw0GAxgpAgAGEAYBAAEBBBESBgUXIBseKC8tJRQQIRwfIhccHyEgJRYENi0UGSAmFg8LCg8Z' +
  'KDxEQzk4NS0iISguLSgmIBcUISAcEQUGCQUQCwYEEh4bHywzLCERE0NEPTc1NTQzQkQwKi4zMzwxLi0mJiUoRFtNUU1JNzU3' +
  'NSMcGx4ZGBgGExoTFBQWHhQEEwgFBQkTFiAoKicgExhTUVNZUVNSRUM/Rj47Sk5RT0tWVVZbYWJdXVpVTz42NDYtIRcZKCAe' +
  'EhoeGiYuJSccCxEGBAYJERkgIyIjIhwhW1FRX1RPSUdUUV9pcH+QjoiAfnJrbHVsaWtnYVVAOC4wIBkZDSZTUlNUU1RVWVhT' +
  'Ty4MBgQGERccJScmJiMgI19TTk9NWnaUoqKdl46ChYaFiY+ThX58bmdwaEs0QjctNDAgGA8EI0ZPVlNdZGZsa2k9CwUECRIa' +
  'HiYnIyMgGyFjUl+MoZeTgHNnWU9KTlRbZGqHnYaMhHpubkk1Oy8wLz85MRsLBAg1U1lTXGZjY11qQgwEAwgUGiAiHxobHh8e' +
  'b4eqnXZfU1JbW1tZVVpkbpCOoY6hjHN3alM7PTgqMDBNTjgmCgMGIUBVUVxjaGRYa0cGBQQKGx4hHxgWHCIeGbWWc2BZXVxh' +
  'XVpWVU5WZmCFrYSaway7wqSAbmRYX1hPQExRNhwNAw00WFZgZGNgWWxGBggECh4iIR8fIB8fFxJ6YW52cmpsbGNjX1xVXWpv' +
  'j7mU4uju+/bq3MezpJWJaUpDX0sqFwQCIlRaYmZjX1psPQoGBBEjLi8qMTkmHxMQYmpxenNqdnVoaGhiW2t3kKupyf/9/Pn2' +
  '7ejiyqmSgmRTRlRFRS4XBhFOXF1bW2NiYjMEBgUfLi0zNj5DKiEXGmdobnZzaW9samdjW1VkgpWvu/j//fz89u/r38KehnBZ' +
  'U0RVTEU8HAMMRWhmXVZcZms2AQYDGzMwKCw/Mx8cGRxzcXl8gHdzcnNvYltacZK3ydT////9/Pjy7Ny4lHdkUUZFSklDQywL' +
  'Cz9oZ2FZXWl3OQAIAh47Nh8cNCwcFhYednN/fHx6eHZ5cmZfXHCXzMX0///9/f317+jUspd4W0c8Q0RRX09RNhY1W2FdWFpj' +
  'cDAABQIcLx4lJSUjGhEaI3l9f3l+fXV3c3FnYV16wM/X/P3////99vLr27SUeFhDPDgxVVRKPUAvPVpcUlNVWHY9EA0JIB4Q' +
  'LjMjHhsXHCJ9goV8f4B5fHZ3cmh2s9231/39///7/Pr17eK6jHNYOTEzICk2LTQ0LTROWFNVUVpqOSUbFikhFCowHxgbDxMg' +
  'hoyMhIeIgYF8eXZrhdfYkMj////9+vr68uTUrYlwWDMtNBkTNyooKiIMGjBPVUxhaEAcGx4oIhsnIRkPDAsMGoeMiX+FjIuO' +
  'gn96aoGsr56o+eDG4PPx5MWJaU5KTT8mJi4bCi0vHhsaCgICFlNLVmROJTE0HhgYHxgeGAwLCxN5hX9xfYaQl4h/eWyAloyV' +
  'quTAhZ3f77NwTERmalU4HiEqHgoNJSITDQ0GBRxPTVViTTEzJQgSIikzKh4MFB4adX16d3+CkpqNgnpyfIWrl7TmyY9krf+T' +
  'L0Jmhio0QDMwJyAMCRYTBQkJBAxKVk5bak4wJhwgGh8jMCwgFiMjGoCBgISHhZSch4J+d3+IqKLG54V9abD7iCZjs61mTzNJ' +
  'RTEcCgULBgYEAwEiTlROYm5AIRwlLBwYGyYuKiAqIRuEgn+GjoeWopWAgHl1f5Wl0efD5K/V7mZAYqyrhlRRbF84FwkDAgMI' +
  'AwIGPlNVU2dvXD4ZISAfHDc5MCYYHBYYcnp1fIV/hIaVgnpvdoSEmcLu9tjb/95gTFqZz9G0qItVKQ8FAgMDCAoCAww4WVNo' +
  'cU4vGhYoLxknKBcQDQ8LEHJ4eoF9eH6CkHJ2cIKPmZeU5//////jbjlSicDQx6GNTBQEBAMDAQ0MAwMLFE9ScngxHx4ZNTEb' +
  'HxYICAsSGxl2eHl8d3eBjH9ufHaCkJaPhdv/////5nEmNn67vqyVekINAwQDAgoKBAIGADVVVHOAORMSHjAjGCcaCQ0YFxoY' +
  'eHx6gnl2gX1zZ3Z6foSOjn3I///5/9lONDhAqLOScFY0EAMEAwIXCQQJABZUUVlvfTgADzE1IyApIhwaGA8PG3NseYJ9eHx6' +
  'cGRzeHOIlol6rf/0ye9+Fh4fH3ahgllCNBICBAIFFggKDB9HVlFVaYA4DRQsKCIhHyUmIBQMDB52c32Gen5/fnBfb3N3joiJ' +
  'f5r/5OPjhT4ZI0VggHhPOTUKAgMCBAUFBCpaTlNSVGp1NxoXICMoGhAUERILCwsQdXWBi3qAenxyYWpxeJSLiYGO9uivgXNg' +
  'MSE2MS5dTTksCQIDAgIFAQBKXFNVT1JjaTERDRwfJhMKCQgJCgoNDXZxgIh/h3p/c2ZvanCQhIWFeufca0xAPSwXFyIJIk4v' +
  'LxQBAwMDBixbaVZTUk5TZ3YxEBkmHCMTCwkKEQsJDA15doF/fYZ4gnFkb2drgHmAfXfQ8nxpl3FTLhkbDCc/Ij0ZAAQEAw0T' +
  'cW9aUlJPWGOHXHOFWjMgGQ0IDBgYEQwMenqHfHaBfIJuZGlkZ3h5gXF8pvPI6vLKklxTW0lbNyM+DwEEAAwbAAZdYVFUSk9f' +
  'hoSxuXpMMSwbCQkQIyAZIHp8hoF6gXyEamRsa2uAeXNsf4TG8vTvu5WVkpVhSyopKQMCAg8hEgMAGV9OTEdDWHZ8mY9hPy8q' +
  'GQwJESMeIjF6foySf4CAhWZjZ3B5joR8bIiCfNT59vjx1qOOVS8UIxIABhcjHgUDBQAaTUlESlNodZB9U0AoHh4hEhkoISc3' +
  'f4ebnn+EhYhqbGhwgoSBgnGBfX+M4Pvv58yHVTQPDRkEDyEoJhIBBAMGABRHQ0lYaWx9XElbOBEYICAnKSYvPHmIk359foGA' +
  'Z2dmcYB+dZWLen58cofj0YyraigeFhkSHC4xNCUEAwQEBAgAFz5NVWh+gV9RaUoMEykwLyooMz13jZV1gX1/gmlsb3GCiHF9' +
  'fJCBhY5+jrOEc1E7OSwfIzxESTEJAwQEBAQFBgEFKFVrnJB2XUlNHxIuMSwnKDE5cYuLdYB6h4lrbmhiaIV8cHB/enh1hX6q' +
  '+neJbFRYiy5HUykDAgUEBAQEBQUFBQAUZL+bhW8zJR4PISonKC0zNHN9dnmBeYh/ZmpkYGR5emhmdnxweo9gw/+fd7Rp1Pg8' +
  'JxYACQQEBQQICgUFBggLAQZLbnNdMB4bDBcnLCwtLSx9iIJ+gX6JemNsZl9sfnhqcHl4Z19gTuf//05+2///TwABFw8EAwIK' +
  'EhIGBQQSGBELAhAvPUUuDwoeKCkqJiYoh5OEfX9+gHVja2ZfcXxya3lgU0tPUmb////OS////4EAHigRCwQNGxoaDwMGGyEf' +
  'GxsaFhcnGwYPJy0pJyAiKomQd3d6f4BzYWpoZoKJZlxSSkVLXUNVpquZiLLYln9GBDUiGhYWHiIgIBAECyInJiUlJSUhFhIL' +
  'FycqMC4jJy6QfXh4dn59bGFmY2eCeUtMS0dGVFYvVaHen41hPhEAOT0xISUeIiUlJSMMARQsLy0uLCUnJiIhGBYmJikqJikt' +
  '2KR4c3V/fm9hZGFkZE1STEVFUVpCMYX9/76lSgwqdlY9MSYnJiYlIyAfDAQhLjY1MSotLywmHxEIECMnJSUqL5bFyo9yen1x' +
  'YGNjYEpTUURGUVNSLEOr//OyiScfqX81PS0qKSwjIiEcFwUSLDE4OTAwMDYzJRAKCwgLISEhKTCEep7Gu5NzZGJnYllHU0tH' +
  'TlFUOzNZwf/1okYKT3kvRzQpLi4wJiMcHBsFGy42PDcwNTY+MBoICgoLCQsNDRIYjIZ2gKvRyY9zZ1ZLP01OTE5STiBEXdz/' +
  'z4ApQmE3PT8qLDM2MSkgHh4gBRsvNzs2MzQ7PSwbCgkJCwoKCwwLC4WBeHx6f5O4z7FOO0NNTk1PUjMaUWL79p5nH05HMUM1' +
  'LC44PTEvIiIZEAQcMz08LS43PzwuGQoKCQoKCwsMDQ16eFlReW5rY26LTyw/T1RMT0kPMEyJ/9B3NCVFNj09LTE0PDk0LyMM' +
  'BQEJJjM9PCYmN0Q3IQsICgoKCwoKCw0NeHVdT3Vsa2lfT0wuQ1RPTU4xAk9At/+wVCVMPzU/NS41ODs5NSkGAQMFGCw2PTYf' +
  'GztDKg8GCAkJCQoKCwsLDXpub2dua2hoYFNCOE5PTE5FEhdZR9D/ljlDSTc2QzMxNjc4ODEwFAIDDyMsNjwxFBFCPSESEwoI' +
  'CgkJCgoLDA2Gc2ZkZ2dpZFxLOUVYT0tLMABETGbV/3VDUT84PT0uMzc5NzQwLykIARAmLTc1KggNQzUoHwwICQkKCgsLCwwM' +
  'gnhraGtpamhSQzxTVU9KQxESW01/3O5YVUc+N0A0LTU5OzYzLSowGgAGIC01MyIDEkQ2LRYGDA0JCQoKCgoNEA==';

// Hand-rolled base64 decoder — no atob/Buffer, so the module depends on zero
// runtime globals and decodes to identical numbers in Node and the browser.
const B64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const B64_INDEX = new Map([...B64_ALPHABET].map((ch, i) => [ch, i] as const));

function decodeBase64(s: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < s.length; i += 4) {
    const n =
      (B64_INDEX.get(s[i])! << 18) |
      (B64_INDEX.get(s[i + 1])! << 12) |
      ((B64_INDEX.get(s[i + 2]) ?? 0) << 6) |
      (B64_INDEX.get(s[i + 3]) ?? 0);
    out.push((n >> 16) & 0xff);
    if (s[i + 2] !== '=' && i + 2 < s.length) out.push((n >> 8) & 0xff);
    if (s[i + 3] !== '=' && i + 3 < s.length) out.push(n & 0xff);
  }
  return out;
}

/** The portrait as a 64x64 matrix of gray levels in [0, 255], row-major. */
export function decodePortrait(): number[][] {
  const flat = decodeBase64(PORTRAIT_B64);
  const rows: number[][] = [];
  for (let i = 0; i < PORTRAIT_H; i++) rows.push(flat.slice(i * PORTRAIT_W, (i + 1) * PORTRAIT_W));
  return rows;
}
